global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [
        'prometheus:9090',
#       'localhost:9090',
#       '127.0.0.1:9090',
        #'host.docker.internal:9090'
      ]
  - job_name: 'backend'
    static_configs:
      - targets: [
        #'host.docker.internal:8000',
        'backend:8000',
      ]


  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

