name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify MySQL connection
      run: |
        mysql --version
        mysql --host 127.0.0.1 --port 3306 -u ${{secrets.MYSQL_ROOT_USER}} -p${{secrets.MYSQL_ROOT_PASSWORD}}

    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Create db env file
      run: |
        echo "${{ secrets.MySql_ENV_FILE}}" > ./db/.env

    - name: Create django_back file
      run: |
        echo "${{ secrets.Django_back_ENV_FILE }} > ./django_back/.env

    - name: Create bookmark env file
      run: |
        echo "{{ secrets.Bookmark_ENV_FILE}}" > ./bookmark/.env
        
